drop table if exists devise CASCADE ;
drop table if exists devise CASCADE ;
drop table if exists devise CASCADE ;
drop table if exists contentieux CASCADE ;
drop table if exists emprunt CASCADE ;
drop table if exists exemplaire CASCADE ;
drop table if exists oeuvre CASCADE ;
drop table if exists personne CASCADE ;
drop table if exists contentieux CASCADE ;
drop table if exists emprunt CASCADE ;
drop table if exists exemplaire CASCADE ;
drop table if exists oeuvre CASCADE ;
drop table if exists personne CASCADE ;
drop table if exists contentieux CASCADE ;
drop table if exists emprunt CASCADE ;
drop table if exists exemplaire CASCADE ;
drop table if exists oeuvre CASCADE ;
drop table if exists personne CASCADE ;
drop table if exists contentieux CASCADE ;
drop table if exists emprunt CASCADE ;
drop table if exists exemplaire CASCADE ;
drop table if exists oeuvre CASCADE ;
drop table if exists personne CASCADE ;
alter table contentieux drop foreign key FK4gu9mln412ycil61a2shaxmby;
alter table emprunt drop foreign key FKjfx335eips4y5tf67ayvwwnqn;
alter table emprunt drop foreign key FKbkqv9xwfy12qiqjtg0u0jv8gw;
alter table emprunt drop foreign key FK6dl58nqo1au3qyypu3399geot;
alter table exemplaire drop foreign key FKgbnkr6frle46m5mu3d2yuxqdr;
drop table if exists contentieux;
drop table if exists emprunt;
drop table if exists exemplaire;
drop table if exists oeuvre;
drop table if exists personne;
alter table contentieux drop foreign key FK4gu9mln412ycil61a2shaxmby;
alter table emprunt drop foreign key FKjfx335eips4y5tf67ayvwwnqn;
alter table emprunt drop foreign key FKbkqv9xwfy12qiqjtg0u0jv8gw;
alter table emprunt drop foreign key FK6dl58nqo1au3qyypu3399geot;
alter table exemplaire drop foreign key FKgbnkr6frle46m5mu3d2yuxqdr;
drop table if exists contentieux;
drop table if exists emprunt;
drop table if exists exemplaire;
drop table if exists oeuvre;
drop table if exists personne;
drop table if exists contentieux CASCADE ;
drop table if exists emprunt CASCADE ;
drop table if exists exemplaire CASCADE ;
drop table if exists oeuvre CASCADE ;
drop table if exists personne CASCADE ;
drop table if exists contentieux CASCADE ;
drop table if exists emprunt CASCADE ;
drop table if exists exemplaire CASCADE ;
drop table if exists oeuvre CASCADE ;
drop table if exists personne CASCADE ;
drop table if exists contentieux CASCADE ;
drop table if exists emprunt CASCADE ;
drop table if exists exemplaire CASCADE ;
drop table if exists oeuvre CASCADE ;
drop table if exists personne CASCADE ;
drop table if exists contentieux CASCADE ;
drop table if exists emprunt CASCADE ;
drop table if exists exemplaire CASCADE ;
drop table if exists oeuvre CASCADE ;
drop table if exists personne CASCADE ;
drop table if exists contentieux CASCADE ;
drop table if exists emprunt CASCADE ;
drop table if exists exemplaire CASCADE ;
drop table if exists oeuvre CASCADE ;
drop table if exists personne CASCADE ;
drop table if exists contentieux CASCADE ;
drop table if exists emprunt CASCADE ;
drop table if exists exemplaire CASCADE ;
drop table if exists oeuvre CASCADE ;
drop table if exists personne CASCADE ;
alter table contentieux drop foreign key FK4gu9mln412ycil61a2shaxmby;
alter table emprunt drop foreign key FKjfx335eips4y5tf67ayvwwnqn;
alter table emprunt drop foreign key FKbkqv9xwfy12qiqjtg0u0jv8gw;
alter table emprunt drop foreign key FK6dl58nqo1au3qyypu3399geot;
alter table exemplaire drop foreign key FKgbnkr6frle46m5mu3d2yuxqdr;
drop table if exists contentieux;
drop table if exists emprunt;
drop table if exists exemplaire;
drop table if exists oeuvre;
drop table if exists personne;
